// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://iplbyepdqbapvdnphqdn.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbGJ5ZXBkcWJhcHZkbnBocWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4MTYxNjIsImV4cCI6MjA0ODM5MjE2Mn0.qGbnlSdgeIKBCWlkQqJFzxdow0YHMh4KNm_sWU4FIMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);